const RAW_DEFAULT_RESERVATION_MINUTES = Number(
  process.env.INVENTORY_RESERVATION_MINUTES
);

const DEFAULT_RESERVATION_MINUTES =
  Number.isFinite(RAW_DEFAULT_RESERVATION_MINUTES) &&
  RAW_DEFAULT_RESERVATION_MINUTES > 0
    ? RAW_DEFAULT_RESERVATION_MINUTES
    : 30;

const PAYMENT_FAILURE_RELEASE_PREFIX = 'PAYMENT_FAILURE_RECOVERY';

module.exports = {
  DEFAULT_RESERVATION_MINUTES,
  PAYMENT_FAILURE_RELEASE_PREFIX,
};
