'use strict';

const RETRYABLE_PAYMENT_INVENTORY_CODES = new Set([
  'INVENTORY_RECOVERY_INCOMPLETE',
  'LEGACY_ALLOCATION_COMPENSATION_FAILED',
  'LEGACY_COMPENSATION_INCOMPLETE',
  'LEGACY_INVENTORY_CONCURRENT_CHANGE',
  'PAYMENT_FAILURE_RECONCILIATION_STOCK_UNAVAILABLE',
  'PAYMENT_FAILURE_RECONCILIATION_CONCURRENT_CHANGE',
  'PAYMENT_FAILURE_LEGACY_RECONCILIATION_INCOMPLETE',
  'PAYMENT_FAILURE_APPROVAL_RECONCILIATION_INCOMPLETE',
  'PAYMENT_FAILURE_RESERVATION_RECONCILIATION_UNAVAILABLE',
  'RESERVED_STOCK_RELEASE_FAILED',
  'RESERVED_STOCK_NOT_AVAILABLE',
  'CONCURRENT_CONFIRMATION_CHANGE',
  'INVENTORY_CONFIRMATION_ERROR',
  'INVENTORY_CONFIRMATION_NOT_READY',
  'INVENTORY_CONFIRMATION_INCONSISTENT',
  'PAYMENT_FAILURE_RECONCILIATION_REQUIRED',
  'PAYMENT_FAILURE_RECONCILIATION_NOT_READY',
  'PAYMENT_FAILURE_RECONCILIATION_INCONSISTENT',
]);

const RETRYABLE_MONGO_CODES = new Set([
  6,
  7,
  50,
  89,
  91,
  112,
  189,
  251,
  262,
  9001,
]);

const RETRYABLE_MONGO_LABELS = new Set([
  'TransientTransactionError',
  'UnknownTransactionCommitResult',
]);

const PERMANENT_PAYMENT_INVENTORY_CODES = new Set([
  'INVALID_PAYMENT_FAILURE_RELEASE_STATUS',
  'PAYMENT_FAILURE_RELEASE_IDENTITY_REQUIRED',
  'PAYMENT_FAILURE_MOVEMENT_MISMATCH',
  'PAYMENT_FAILURE_RESERVATION_OWNERSHIP_MISMATCH',
  'PAYMENT_FAILURE_RESERVATION_NOT_RECONCILABLE',
  'PAYMENT_FAILURE_RESERVATION_TERMINAL_EVIDENCE',
  'PAYMENT_FAILURE_RESERVATION_ITEM_INVALID',
  'PAYMENT_FAILURE_RESERVATION_RECONCILER_REQUIRED',
  'LEGACY_INVENTORY_ALLOCATIONS_REQUIRED',
  'LEGACY_ALLOCATION_INCOMPLETE',
  'LEGACY_DISCOUNT_EVIDENCE_MISSING',
  'LEGACY_INVENTORY_STOCK_NOT_FOUND',
  'LEGACY_INVENTORY_ALLOCATION_MISMATCH',
  'PAYMENT_FAILURE_COMPENSATION_MOVEMENT_MISSING',
  'PAYMENT_FAILURE_COMPENSATION_QUANTITY_MISMATCH',
  'PAYMENT_FAILURE_RECONCILIATION_STOCK_MISSING',
  'PAYMENT_FAILURE_RECONCILIATION_STOCK_MISMATCH',
  'PAYMENT_FAILURE_RECONCILIATION_ALLOCATION_MISMATCH',
  'CONFIRMED_RESERVATION_CANNOT_BE_RELEASED',
  'RESERVATION_RELEASE_EVIDENCE_MISMATCH',
  'RESERVATION_EXPIRED',
  'RESERVATION_NOT_FOUND',
  'UNVERIFIED_PAYMENT_APPROVAL',
]);

const PAYMENT_INVENTORY_TRANSACTION_MAX_ATTEMPTS = 3;

module.exports = {
  PAYMENT_INVENTORY_TRANSACTION_MAX_ATTEMPTS,
  PERMANENT_PAYMENT_INVENTORY_CODES,
  RETRYABLE_MONGO_CODES,
  RETRYABLE_MONGO_LABELS,
  RETRYABLE_PAYMENT_INVENTORY_CODES,
};
