// frontend/src/admin/dashboard/dashboardStyles.js

export const dashboardStyles = {
  page: {},
  title: {},
  muted: {},
  eyebrow: {},
  hero: {},
  heroIcon: {},
  heroMedia: {},
  actionButton: {},
  primaryChip: {},
  card: {},
  kpiCard: {},
  kpiIcon: {},
  warningIcon: {},
  chartCard: {},
  alertItem: {},
  progressTrack: {},
  progressFill: {},
  statusSuccess: {},
  statusWarning: {},
  statusInfo: {},
  statusDanger: {},
};
