'use strict';

const STORE_CREDIT_ACCESS_VERSION = 1;
const STORE_CREDIT_ACCESS_TTL_MS = 10 * 60 * 1000;
const STORE_CREDIT_RESERVATION_TTL_MS = 20 * 60 * 1000;

module.exports = {
  STORE_CREDIT_ACCESS_TTL_MS,
  STORE_CREDIT_ACCESS_VERSION,
  STORE_CREDIT_RESERVATION_TTL_MS,
};
