'use strict';

/*
 * La agregación administrativa no hereda `select: false` de Mongoose. Esta
 * proyección inclusiva define el único subconjunto de Order que puede salir
 * de MongoDB hacia el listado. Los datos operativos de fulfillment se usan
 * para calcular la cola, pero nunca forman parte del DTO HTTP.
 */
const ADMIN_ORDER_LIST_DB_PROJECTION = Object.freeze({
  _id: 1,
  orderNumber: 1,
  status: 1,
  source: 1,
  channel: 1,
  saleType: 1,
  total: 1,
  subtotal: 1,
  shipping: 1,
  summary: 1,
  'customer.name': 1,
  'customer.lastname': 1,
  'customer.emailOrPhone': 1,
  'customer.email': 1,
  'customer.phone': 1,
  'payment.provider': 1,
  'payment.providerLabel': 1,
  'payment.status': 1,
  'payment.method': 1,
  'payment.methodLabel': 1,
  'payment.currency': 1,
  'pos.receiptNumber': 1,
  'exchangeOrigin.type': 1,
  'exchangeOrigin.originalOrderNumber': 1,
  'exchangeOrigin.returnNumber': 1,
  'exchangeOrigin.noCharge': 1,
  tags: 1,
  printed: 1,
  archived: 1,
  branch: 1,
  branchSnapshot: 1,
  'inventoryAllocations.branch': 1,
  'inventoryAllocations.branchSnapshot': 1,
  'inventoryAllocations.soldQuantity': 1,
  'inventoryAllocations.returnedQuantity': 1,
  'fulfillment.shipments.status': 1,
  'fulfillment.shipments.incidents.status': 1,
  'fulfillment.shipments.sla.pickingDueAt': 1,
  'fulfillment.shipments.sla.dispatchDueAt': 1,
  'fulfillment.shipments.sla.deliveryDueAt': 1,
  'fulfillment.shipments.sla.breachedAt': 1,
  'items._id': 1,
  'items.product': 1,
  'items.productId': 1,
  'items.title': 1,
  'items.image': 1,
  'items.color': 1,
  'items.colorLabel': 1,
  'items.size': 1,
  'items.qty': 1,
  'items.quantity': 1,
  'items.price': 1,
  'items.unitPrice': 1,
  'items.priceNumber': 1,
  'items.variantId': 1,
  'items.variantKey': 1,
  'items.variantLabel': 1,
  'items.variantAttributes': 1,
  'items.variantSku': 1,
  'items.variantBarcode': 1,
  'items.productType': 1,
  'items.requiresShipping': 1,
  'items.fulfillmentKind': 1,
  'cart._id': 1,
  'cart.productId': 1,
  'cart.title': 1,
  'cart.image': 1,
  'cart.color': 1,
  'cart.colorLabel': 1,
  'cart.size': 1,
  'cart.quantity': 1,
  'cart.price': 1,
  'cart.variantId': 1,
  'cart.variantKey': 1,
  'cart.variantLabel': 1,
  'cart.variantAttributes': 1,
  createdAt: 1,
  updatedAt: 1,
});

const ADMIN_ORDER_CSV_DB_PROJECTION = Object.freeze({
  _id: 1,
  orderNumber: 1,
  'customer.name': 1,
  'customer.lastname': 1,
  'customer.emailOrPhone': 1,
  'customer.email': 1,
  summary: 1,
  'items.qty': 1,
  'items.quantity': 1,
  'items.price': 1,
  'items.unitPrice': 1,
  'items.priceNumber': 1,
  'cart.quantity': 1,
  'cart.price': 1,
  total: 1,
  shipping: 1,
  status: 1,
  tags: 1,
  createdAt: 1,
  updatedAt: 1,
});

function buildAdminOrderListProjectionStage() {
  return { $project: { ...ADMIN_ORDER_LIST_DB_PROJECTION } };
}

module.exports = {
  ADMIN_ORDER_CSV_DB_PROJECTION,
  ADMIN_ORDER_LIST_DB_PROJECTION,
  buildAdminOrderListProjectionStage,
};
